Evoluzione_Doxygen_Base: group17.weatherviewer.CurrentWeather Class Reference
group17.weatherviewer.CurrentWeather Class Reference
Public Member Functions
CurrentWeather (String CityName) throws UnsupportedEncodingException
String getCity ()
String getWindSpeed ()
String getPressure ()
String getHumidity ()
String getSunriseTime ()
String getSunsetTime ()
String getWindDirection ()
String getTemp ()
String getTempC ()
String getTempF ()
String getTempMax ()
String getMaxTempC ()
String getTempMaxF ()
String getTempMin ()
String getTempMinC ()
String getTempMinF ()
String getCountry ()
String getSkyCondition ()
Static Public Member Functions
static void main (String[] args)
Package Attributes
String Sky
String Sunrise
String Sunset
String Country
double Pressure
double Humidity
double TempMax
double TempMin
double WindSpeed
double WindDir
Private Attributes
String City
double Temp
Detailed Description
Definition at line 14 of file CurrentWeather.java.
Constructor & Destructor Documentation
CurrentWeather()
group17.weatherviewer.CurrentWeather.CurrentWeather (String CityName) throws UnsupportedEncodingException inline
Constructor for CurrentWeather Takes a City name as parameter, retrieves and parses the JSON for that city and stores the data
Parameters
CityName is the name of the city for which we're storing and parsing information
Exceptions
UnsupportedEncodingException if the JSOn retrieval fails
Definition at line 27 of file CurrentWeather.java.
Referenced by group17.weatherviewer.CurrentWeather.main().
Member Function Documentation
getCity()
String group17.weatherviewer.CurrentWeather.getCity () inline
Getter method for City
Returns
the city from which this weather data was gathered
Definition at line 96 of file CurrentWeather.java.
References group17.weatherviewer.CurrentWeather.City.
Referenced by group17.weatherviewer.CurrentWeather.main(), and group17.weatherviewer.MainFrame.refresh().
getCountry()
String group17.weatherviewer.CurrentWeather.getCountry () inline
Getter method for country name
Returns
the name of the country the city is in
Definition at line 214 of file CurrentWeather.java.
References group17.weatherviewer.CurrentWeather.Country.
Referenced by group17.weatherviewer.CurrentWeather.main(), and group17.weatherviewer.MainFrame.refresh().
getHumidity()
String group17.weatherviewer.CurrentWeather.getHumidity () inline
Getter method for Humidity
Returns
the current humidity in %
Definition at line 120 of file CurrentWeather.java.
Referenced by group17.weatherviewer.CurrentWeather.main(), and group17.weatherviewer.MainFrame.refresh().
getMaxTempC()
String group17.weatherviewer.CurrentWeather.getMaxTempC () inline
Getter method for max Celsius temperature
Returns
the current max temp in degrees C
Definition at line 178 of file CurrentWeather.java.
Referenced by group17.weatherviewer.CurrentWeather.getTempMax().
getPressure()
String group17.weatherviewer.CurrentWeather.getPressure () inline
Getter method for Pressure
Returns
the current pressure
Definition at line 112 of file CurrentWeather.java.
Referenced by group17.weatherviewer.CurrentWeather.main(), and group17.weatherviewer.MainFrame.refresh().
getSkyCondition()
String group17.weatherviewer.CurrentWeather.getSkyCondition () inline
Getter method for sky condition
Returns
a string representing sky condition
Definition at line 222 of file CurrentWeather.java.
References group17.weatherviewer.CurrentWeather.Sky.
Referenced by group17.weatherviewer.CurrentWeather.main(), and group17.weatherviewer.MainFrame.refresh().
getSunriseTime()
String group17.weatherviewer.CurrentWeather.getSunriseTime () inline
Getter method for Sunrise
Returns
the current Sunrise time in Unix time
Definition at line 127 of file CurrentWeather.java.
References group17.weatherviewer.CurrentWeather.Sunrise.
Referenced by group17.weatherviewer.CurrentWeather.main(), and group17.weatherviewer.MainFrame.refresh().
getSunsetTime()
String group17.weatherviewer.CurrentWeather.getSunsetTime () inline
Getter method for Sunset
Returns
the current Sunset time in Unix time
Definition at line 134 of file CurrentWeather.java.
References group17.weatherviewer.CurrentWeather.Sunset.
Referenced by group17.weatherviewer.CurrentWeather.main(), and group17.weatherviewer.MainFrame.refresh().
getTemp()
String group17.weatherviewer.CurrentWeather.getTemp () inline
Getter method for Celsius temperature
Returns
the current temp in degrees C (will be only Temp method in later versions)
Definition at line 149 of file CurrentWeather.java.
References group17.weatherviewer.CurrentWeather.getTempC().
Referenced by group17.weatherviewer.CurrentWeather.main(), and group17.weatherviewer.MainFrame.refresh().
getTempC()
String group17.weatherviewer.CurrentWeather.getTempC () inline
Helper method for Celsius temperature
Returns
the current temp in degrees C (will phase this out in later versions)
Definition at line 156 of file CurrentWeather.java.
Referenced by group17.weatherviewer.CurrentWeather.getTemp().
getTempF()
String group17.weatherviewer.CurrentWeather.getTempF () inline
Getter method for Fahrenheit temperature
Returns
the current temp in degrees F (will phase this out in later versions)
Definition at line 163 of file CurrentWeather.java.
getTempMax()
String group17.weatherviewer.CurrentWeather.getTempMax () inline
Getter method for max Celsius temperature Same story as getTemp()s, will be the only getTempMax method later.
Returns
the current max temp in degrees C
Definition at line 171 of file CurrentWeather.java.
References group17.weatherviewer.CurrentWeather.getMaxTempC().
Referenced by group17.weatherviewer.CurrentWeather.main(), and group17.weatherviewer.MainFrame.refresh().
getTempMaxF()
String group17.weatherviewer.CurrentWeather.getTempMaxF () inline
Getter method for max F temperature
Returns
the current max temp in degrees F
Definition at line 185 of file CurrentWeather.java.
getTempMin()
String group17.weatherviewer.CurrentWeather.getTempMin () inline
Getter method for min Celsius temperature Same story as getTemp()s, will be the only getTempMax method later.
Returns
the current min temp in degrees C
Definition at line 193 of file CurrentWeather.java.
References group17.weatherviewer.CurrentWeather.getTempMinC().
Referenced by group17.weatherviewer.CurrentWeather.main(), and group17.weatherviewer.MainFrame.refresh().
getTempMinC()
String group17.weatherviewer.CurrentWeather.getTempMinC () inline
Getter method for min Celsius temperature
Returns
the current min temp in degrees C
Definition at line 200 of file CurrentWeather.java.
Referenced by group17.weatherviewer.CurrentWeather.getTempMin().
getTempMinF()
String group17.weatherviewer.CurrentWeather.getTempMinF () inline
Getter method for min F temperature
Returns
the current min temp in degrees f
Definition at line 207 of file CurrentWeather.java.
getWindDirection()
String group17.weatherviewer.CurrentWeather.getWindDirection () inline
Getter method for wind direction
Returns
the current wind direction in degrees
Definition at line 141 of file CurrentWeather.java.
Referenced by group17.weatherviewer.CurrentWeather.main(), and group17.weatherviewer.MainFrame.refresh().
getWindSpeed()
String group17.weatherviewer.CurrentWeather.getWindSpeed () inline
Getter method for WindSpeed
Returns
the current wind speed
Definition at line 105 of file CurrentWeather.java.
Referenced by group17.weatherviewer.CurrentWeather.main(), and group17.weatherviewer.MainFrame.refresh().
main()
static void group17.weatherviewer.CurrentWeather.main (String [] args) inline static
Purely for testing purposes, will be taken out in later versions.
Parameters
args command line arguments
Definition at line 279 of file CurrentWeather.java.
References group17.weatherviewer.CurrentWeather.CurrentWeather(), group17.weatherviewer.CurrentWeather.getCity(), group17.weatherviewer.CurrentWeather.getCountry(), group17.weatherviewer.CurrentWeather.getHumidity(), group17.weatherviewer.CurrentWeather.getPressure(), group17.weatherviewer.CurrentWeather.getSkyCondition(), group17.weatherviewer.CurrentWeather.getSunriseTime(), group17.weatherviewer.CurrentWeather.getSunsetTime(), group17.weatherviewer.CurrentWeather.getTemp(), group17.weatherviewer.CurrentWeather.getTempMax(), group17.weatherviewer.CurrentWeather.getTempMin(), group17.weatherviewer.CurrentWeather.getWindDirection(), and group17.weatherviewer.CurrentWeather.getWindSpeed().
Field Documentation
City
String group17.weatherviewer.CurrentWeather.City private
Definition at line 17 of file CurrentWeather.java.
Referenced by group17.weatherviewer.CurrentWeather.getCity().
Country
String group17.weatherviewer.CurrentWeather.Country package
Definition at line 17 of file CurrentWeather.java.
Referenced by group17.weatherviewer.CurrentWeather.getCountry().
Humidity
double group17.weatherviewer.CurrentWeather.Humidity package
Definition at line 18 of file CurrentWeather.java.
Pressure
double group17.weatherviewer.CurrentWeather.Pressure package
Definition at line 18 of file CurrentWeather.java.
Sky
String group17.weatherviewer.CurrentWeather.Sky package
Definition at line 17 of file CurrentWeather.java.
Referenced by group17.weatherviewer.CurrentWeather.getSkyCondition().
Sunrise
String group17.weatherviewer.CurrentWeather.Sunrise package
Definition at line 17 of file CurrentWeather.java.
Referenced by group17.weatherviewer.CurrentWeather.getSunriseTime().
Sunset
String group17.weatherviewer.CurrentWeather.Sunset package
Definition at line 17 of file CurrentWeather.java.
Referenced by group17.weatherviewer.CurrentWeather.getSunsetTime().
Temp
double group17.weatherviewer.CurrentWeather.Temp private
Definition at line 18 of file CurrentWeather.java.
TempMax
double group17.weatherviewer.CurrentWeather.TempMax package
Definition at line 18 of file CurrentWeather.java.
TempMin
double group17.weatherviewer.CurrentWeather.TempMin package
Definition at line 18 of file CurrentWeather.java.
WindDir
double group17.weatherviewer.CurrentWeather.WindDir package
Definition at line 18 of file CurrentWeather.java.
WindSpeed
double group17.weatherviewer.CurrentWeather.WindSpeed package
Definition at line 18 of file CurrentWeather.java.
The documentation for this class was generated from the following file:
weatherviewer/CurrentWeather.java