Evoluzione_Doxygen_Base: group17.weatherviewer.MainFrame.AddLocation Class Reference
group17.weatherviewer.MainFrame.AddLocation Class Reference
Public Member Functions
AddLocation (JButton button)
void actionPerformed (ActionEvent e)
void insertUpdate (DocumentEvent e)
void removeUpdate (DocumentEvent e)
void changedUpdate (DocumentEvent e)
Protected Member Functions
boolean alreadyInList (String name)
Private Member Functions
void enableButton ()
boolean handleEmptyTextField (DocumentEvent e)
Private Attributes
boolean alreadyEnabled = false
JButton button
CurrentWeather test
Detailed Description
Class representing the action listener for adding locations to the list
Definition at line 1295 of file MainFrame.java.
Constructor & Destructor Documentation
AddLocation()
group17.weatherviewer.MainFrame.AddLocation.AddLocation (JButton button) inline
constructor for AddLocation
Parameters
button JButton where the actionlistener is called from
Definition at line 1306 of file MainFrame.java.
References group17.weatherviewer.MainFrame.AddLocation.button.
Member Function Documentation
actionPerformed()
void group17.weatherviewer.MainFrame.AddLocation.actionPerformed (ActionEvent e) inline
overrided ActionListener interface method which is executed whenever an event is fired
Parameters
e the event fired that caused the method call
Definition at line 1315 of file MainFrame.java.
References group17.weatherviewer.UserPreferences.addLocation(), group17.weatherviewer.MainFrame.AddLocation.alreadyInList(), group17.weatherviewer.CurrentWeather.getCity(), and group17.weatherviewer.CurrentWeather.getCountry().
alreadyInList()
boolean group17.weatherviewer.MainFrame.AddLocation.alreadyInList (String name) inline protected
checks to see if the city being added is already in the list
Parameters
name the name of the city being added
Returns
whether or not city is in the list
Definition at line 1371 of file MainFrame.java.
Referenced by group17.weatherviewer.MainFrame.AddLocation.actionPerformed().
changedUpdate()
void group17.weatherviewer.MainFrame.AddLocation.changedUpdate (DocumentEvent e) inline
overrides documentListener method
Parameters
e document event
Definition at line 1402 of file MainFrame.java.
References group17.weatherviewer.MainFrame.AddLocation.enableButton(), and group17.weatherviewer.MainFrame.AddLocation.handleEmptyTextField().
enableButton()
void group17.weatherviewer.MainFrame.AddLocation.enableButton () inline private
enables addLocation button
Definition at line 1411 of file MainFrame.java.
Referenced by group17.weatherviewer.MainFrame.AddLocation.changedUpdate(), and group17.weatherviewer.MainFrame.AddLocation.insertUpdate().
handleEmptyTextField()
boolean group17.weatherviewer.MainFrame.AddLocation.handleEmptyTextField (DocumentEvent e) inline private
handles empty text field
Definition at line 1420 of file MainFrame.java.
Referenced by group17.weatherviewer.MainFrame.AddLocation.changedUpdate(), and group17.weatherviewer.MainFrame.AddLocation.removeUpdate().
insertUpdate()
void group17.weatherviewer.MainFrame.AddLocation.insertUpdate (DocumentEvent e) inline
Definition at line 1381 of file MainFrame.java.
References group17.weatherviewer.MainFrame.AddLocation.enableButton().
removeUpdate()
void group17.weatherviewer.MainFrame.AddLocation.removeUpdate (DocumentEvent e) inline
overrides documentListener method
Parameters
e document event
Definition at line 1392 of file MainFrame.java.
References group17.weatherviewer.MainFrame.AddLocation.handleEmptyTextField().
Field Documentation
alreadyEnabled
boolean group17.weatherviewer.MainFrame.AddLocation.alreadyEnabled = false private
Definition at line 1297 of file MainFrame.java.
button
JButton group17.weatherviewer.MainFrame.AddLocation.button private
Definition at line 1298 of file MainFrame.java.
Referenced by group17.weatherviewer.MainFrame.AddLocation.AddLocation().
test
CurrentWeather group17.weatherviewer.MainFrame.AddLocation.test private
Definition at line 1300 of file MainFrame.java.
The documentation for this class was generated from the following file:
weatherviewer/MainFrame.java