Evoluzione_Doxygen_Base: group17.weatherviewer.MainFrame Class Reference
group17.weatherviewer.MainFrame Class Reference
Data Structures
class AddLocation
Public Member Functions
MainFrame ()
void refresh (String location)
void toggleShortTerm (boolean b)
void setSkyConditionImages (int ID)
Static Public Member Functions
static void main (String[] args)
Private Member Functions
void initialize ()
void createFont ()
void setTemperatureFields ()
void updateShortTerm ()
void updateLongTerm ()
Private Attributes
JFrame frame
ImageIcon backgroundImage
String skyConditionIconLarge
String skyConditionIconSmall
String skyConditionBackground
JLabel backgroundLabel
JTextField textField
JTextField barSearch
JScrollPane scrollPane
JButton buttonFavourite
JButton buttonLongTerm
JButton buttonShortTerm
JButton buttonRefresh
JButton buttonToCelsius
JButton buttonToFahrenheit
JLabel labelSkyConditionIcon
JLabel labelAirPressure
JLabel labelSunrise
JLabel labelSunset
JLabel labelSky
JLabel labelWind
JLabel labelHumidity
JLabel labelLocation
JLabel labelPrecipitation
JLabel labelTempInfo
JLabel labelWindInfo
JLabel labelHumidityInfo
JLabel labelAirPressureInfo
JLabel labelCurrentMMTempInfo
JLabel labelSunriseInfo
JLabel labelSunsetInfo
JLabel labelSkyConditionInfo
JLabel labelPrecipitationInfo
JLabel labelUpdated
JLabel labelUpdatedInfo
JLabel label12AM
JLabel label12AMSkyConditionIcon
JLabel label12AMTempInfo
JLabel label12AMSkyConditionInfo
JLabel label12AMPrecipitation
JLabel label3AM
JLabel label3AMSkyConditionIcon
JLabel label3AMTempInfo
JLabel label3AMSkyConditionInfo
JLabel label3AMPrecipitation
JLabel label6AM
JLabel label6AMSkyConditionIcon
JLabel label6AMTempInfo
JLabel label6AMSkyConditionInfo
JLabel label6AMPrecipitation
JLabel label9AM
JLabel label9AMSkyConditionIcon
JLabel label9AMTempInfo
JLabel label9AMSkyConditionInfo
JLabel label9AMPrecipitation
JLabel label12PM
JLabel label12PMSkyConditionIcon
JLabel label12PMTempInfo
JLabel label12PMSkyConditionInfo
JLabel label12PMPrecipitation
JLabel label3PM
JLabel label3PMSkyConditionIcon
JLabel label3PMTempInfo
JLabel label3PMSkyConditionInfo
JLabel label3PMPrecipitation
JLabel label6PM
JLabel label6PMSkyConditionIcon
JLabel label6PMTempInfo
JLabel label6PMSkyConditionInfo
JLabel label6PMPrecipitation
JLabel label9PM
JLabel label9PMSkyConditionIcon
JLabel label9PMTempInfo
JLabel label9PMSkyConditionInfo
JLabel label9PMPrecipitation
JLabel labelDay1Info
JLabel labelDay1TempInfo
JLabel labelDay1MMTempInfo
JLabel labelDay1SkyConditionIcon
JLabel labelDay1SkyConditionInfo
JLabel labelDay1PrecipitationInfo
JLabel labelDay2Info
JLabel labelDay2TempInfo
JLabel labelDay2MMTempInfo
JLabel labelDay2SkyConditionInfo
JLabel labelDay2SkyConditionIcon
JLabel labelDay2PrecipitationInfo
JLabel labelDay3Info
JLabel labelDay3TempInfo
JLabel labelDay3MMTempInfo
JLabel labelDay3SkyConditionInfo
JLabel labelDay3SkyConditionIcon
JLabel labelDay3PrecipitationInfo
JLabel labelDay4Info
JLabel labelDay4TempInfo
JLabel labelDay4MMTempInfo
JLabel labelDay4SkyConditionInfo
JLabel labelDay4SkyConditionIcon
JLabel labelDay4PrecipitationInfo
JLabel labelDay5Info
JLabel labelDay5TempInfo
JLabel labelDay5MMTempInfo
JLabel labelDay5SkyConditionInfo
JLabel labelDay5SkyConditionIcon
JLabel labelDay5PrecipitationInfo
JLabel labelDay6Info
JLabel labelDay6TempInfo
JLabel labelDay6MMTempInfo
JLabel labelDay6SkyConditionInfo
JLabel labelDay6SkyConditionIcon
JLabel labelDay6PrecipitationInfo
JLabel labelDay7Info
JLabel labelDay7TempInfo
JLabel labelDay7MMTempInfo
JLabel labelDay7SkyConditionInfo
JLabel labelDay7SkyConditionIcon
JLabel labelDay7PrecipitationInfo
DateFormat dateFormat
Calendar cal
String lastUpdated
JList listLocations
DefaultListModel listModel
UserPreferences prefs
CurrentWeather currentWeather
ShortTermForecast shortTermForecast
LongTermForecast longTermForecast
ArrayList< JLabel > shortTermTime = new ArrayList<JLabel>()
ArrayList< JLabel > shortTermIcon = new ArrayList<JLabel>()
ArrayList< JLabel > shortTermSkyCon = new ArrayList<JLabel>()
ArrayList< JLabel > shortTermTemp = new ArrayList<JLabel>()
ArrayList< JLabel > shortTermPrecip = new ArrayList<JLabel>()
ArrayList< JLabel > longTermDate = new ArrayList<JLabel>()
ArrayList< JLabel > longTermIcon = new ArrayList<JLabel>()
ArrayList< JLabel > longTermSkyCon = new ArrayList<JLabel>()
ArrayList< JLabel > longTermTemp = new ArrayList<JLabel>()
ArrayList< JLabel > longTermHighLow = new ArrayList<JLabel>()
ArrayList< JLabel > longTermPrecip = new ArrayList<JLabel>()
Static Private Attributes
static Font font
Detailed Description
Definition at line 20 of file MainFrame.java.
Constructor & Destructor Documentation
MainFrame()
group17.weatherviewer.MainFrame.MainFrame () inline
Create the application.
Definition at line 195 of file MainFrame.java.
References group17.weatherviewer.MainFrame.initialize().
Referenced by group17.weatherviewer.MainFrame.main().
Member Function Documentation
createFont()
void group17.weatherviewer.MainFrame.createFont () inline private
called once by the constructor to initialize font data from file before drawing
Definition at line 1163 of file MainFrame.java.
Referenced by group17.weatherviewer.MainFrame.initialize().
initialize()
void group17.weatherviewer.MainFrame.initialize () inline private
Initialize the contents of the frame.
BEGIN INITIALIZING FRAME ///
END INITIALIZING FRAME ///
BEGIN INITIALIZING LOCAL WEATHER VIEW PANEL ///
END INITIALIZATION OF LOCAL WEATHER VIEW PANEL ///
BEGIN INITIALIZATION OF LOCATIONS PANEL ///
END INITIALIZATION OF LOCATIONS PANEL ///
BEGIN INITIALIZATION OF SHORT-TERM FORECAST PANEL ///
END INITIALIZATION OF SHORT-TERM FORECAST PANEL ///
BEGIN INITIALIZATION OF LONG-TERM FORECAST PANEL ///
END INITIALIZATION OF LONG-TERM CONDITIONS ///
Definition at line 202 of file MainFrame.java.
References group17.weatherviewer.MainFrame.createFont(), group17.weatherviewer.UserPreferences.getDefaultLocation(), group17.weatherviewer.UserPreferences.getLocations(), group17.weatherviewer.UserPreferences.getPrefs(), group17.weatherviewer.UserPreferences.getTempUnit(), group17.weatherviewer.MainFrame.refresh(), group17.weatherviewer.UserPreferences.savePrefs(), group17.weatherviewer.UserPreferences.setDefaultLocation(), group17.weatherviewer.MainFrame.setTemperatureFields(), group17.weatherviewer.UserPreferences.setTempUnit(), and group17.weatherviewer.MainFrame.toggleShortTerm().
Referenced by group17.weatherviewer.MainFrame.MainFrame().
main()
static void group17.weatherviewer.MainFrame.main (String [] args) inline static
Launch the application.
Definition at line 178 of file MainFrame.java.
References group17.weatherviewer.MainFrame.frame, and group17.weatherviewer.MainFrame.MainFrame().
refresh()
void group17.weatherviewer.MainFrame.refresh (String location) inline
refreshes the weather data throughout the UI
Parameters
location the city for which we are viewing weather data
Definition at line 1179 of file MainFrame.java.
References group17.weatherviewer.CurrentWeather.getCity(), group17.weatherviewer.CurrentWeather.getCountry(), group17.weatherviewer.CurrentWeather.getHumidity(), group17.weatherviewer.CurrentWeather.getPressure(), group17.weatherviewer.CurrentWeather.getSkyCondition(), group17.weatherviewer.CurrentWeather.getSunriseTime(), group17.weatherviewer.CurrentWeather.getSunsetTime(), group17.weatherviewer.ShortTermForecast.getTotalPrecipitation(), group17.weatherviewer.CurrentWeather.getWeatherID(), group17.weatherviewer.CurrentWeather.getWindDirection(), group17.weatherviewer.CurrentWeather.getWindSpeed(), group17.weatherviewer.MainFrame.setSkyConditionImages(), group17.weatherviewer.MainFrame.setTemperatureFields(), group17.weatherviewer.MainFrame.updateLongTerm(), and group17.weatherviewer.MainFrame.updateShortTerm().
Referenced by group17.weatherviewer.MainFrame.initialize().
setSkyConditionImages()
void group17.weatherviewer.MainFrame.setSkyConditionImages (int ID) inline
takes a parameter ID obtained from the weather API and sets the corresponding sky condition icons to match the sky condition described by the ID. unfortunately doing this manually using a switch is still the easiest way to do this.
Parameters
ID the ID number describing the sky condition
Definition at line 1487 of file MainFrame.java.
Referenced by group17.weatherviewer.MainFrame.refresh(), group17.weatherviewer.MainFrame.updateLongTerm(), and group17.weatherviewer.MainFrame.updateShortTerm().
setTemperatureFields()
void group17.weatherviewer.MainFrame.setTemperatureFields () inline private
Sets all the temperature fields in the interface. This is called when data is refreshed, but also when C/F unit is changed - which is why it is kept seperate from non-temperature fields.
Definition at line 1231 of file MainFrame.java.
References group17.weatherviewer.LongTermForecast.LongTermWeather.getHigh(), group17.weatherviewer.LongTermForecast.getLongTermForecast(), group17.weatherviewer.LongTermForecast.LongTermWeather.getLow(), group17.weatherviewer.CurrentWeather.getMaxTemp(), group17.weatherviewer.CurrentWeather.getMinTemp(), group17.weatherviewer.ShortTermForecast.getShortTermForecast(), group17.weatherviewer.ShortTermForecast.ShortTermWeather.getTemp(), group17.weatherviewer.LongTermForecast.LongTermWeather.getTemp(), group17.weatherviewer.CurrentWeather.getTemp(), and group17.weatherviewer.UserPreferences.getTempUnit().
Referenced by group17.weatherviewer.MainFrame.initialize(), and group17.weatherviewer.MainFrame.refresh().
toggleShortTerm()
void group17.weatherviewer.MainFrame.toggleShortTerm (boolean b) inline
toggles whether the short or long term display is shown
Parameters
b whether to show or hide short term (ie, true shows short term, false shows long term)
Definition at line 1434 of file MainFrame.java.
Referenced by group17.weatherviewer.MainFrame.initialize().
updateLongTerm()
void group17.weatherviewer.MainFrame.updateLongTerm () inline private
updates the long term weather forecast values when the location is changed / data is refreshed (except temperatures since these are handled in setTemperatureFields)
Definition at line 1274 of file MainFrame.java.
References group17.weatherviewer.LongTermForecast.LongTermWeather.getDate(), group17.weatherviewer.LongTermForecast.getLongTermForecast(), group17.weatherviewer.LongTermForecast.LongTermWeather.getRain(), group17.weatherviewer.LongTermForecast.LongTermWeather.getSkyCondition(), group17.weatherviewer.LongTermForecast.LongTermWeather.getSnow(), group17.weatherviewer.LongTermForecast.LongTermWeather.getWeatherID(), and group17.weatherviewer.MainFrame.setSkyConditionImages().
Referenced by group17.weatherviewer.MainFrame.refresh().
updateShortTerm()
void group17.weatherviewer.MainFrame.updateShortTerm () inline private
updates the short term weather forecast values when the location is changed / data is refreshed (except temperatures since these are handled in setTemperatureFields)
Definition at line 1253 of file MainFrame.java.
References group17.weatherviewer.ShortTermForecast.ShortTermWeather.getRain(), group17.weatherviewer.ShortTermForecast.getShortTermForecast(), group17.weatherviewer.ShortTermForecast.ShortTermWeather.getSkyCondition(), group17.weatherviewer.ShortTermForecast.ShortTermWeather.getSnow(), group17.weatherviewer.ShortTermForecast.ShortTermWeather.getTime(), group17.weatherviewer.ShortTermForecast.ShortTermWeather.getWeatherID(), and group17.weatherviewer.MainFrame.setSkyConditionImages().
Referenced by group17.weatherviewer.MainFrame.refresh().
Field Documentation
backgroundImage
ImageIcon group17.weatherviewer.MainFrame.backgroundImage private
Definition at line 28 of file MainFrame.java.
backgroundLabel
JLabel group17.weatherviewer.MainFrame.backgroundLabel private
Definition at line 33 of file MainFrame.java.
barSearch
JTextField group17.weatherviewer.MainFrame.barSearch private
Definition at line 36 of file MainFrame.java.
buttonFavourite
JButton group17.weatherviewer.MainFrame.buttonFavourite private
Definition at line 40 of file MainFrame.java.
buttonLongTerm
JButton group17.weatherviewer.MainFrame.buttonLongTerm private
Definition at line 41 of file MainFrame.java.
buttonRefresh
JButton group17.weatherviewer.MainFrame.buttonRefresh private
Definition at line 43 of file MainFrame.java.
buttonShortTerm
JButton group17.weatherviewer.MainFrame.buttonShortTerm private
Definition at line 42 of file MainFrame.java.
buttonToCelsius
JButton group17.weatherviewer.MainFrame.buttonToCelsius private
Definition at line 44 of file MainFrame.java.
buttonToFahrenheit
JButton group17.weatherviewer.MainFrame.buttonToFahrenheit private
Definition at line 45 of file MainFrame.java.
cal
Calendar group17.weatherviewer.MainFrame.cal private
Definition at line 150 of file MainFrame.java.
currentWeather
CurrentWeather group17.weatherviewer.MainFrame.currentWeather private
Definition at line 158 of file MainFrame.java.
dateFormat
DateFormat group17.weatherviewer.MainFrame.dateFormat private
Definition at line 149 of file MainFrame.java.
font
Font group17.weatherviewer.MainFrame.font static private
Definition at line 24 of file MainFrame.java.
frame
JFrame group17.weatherviewer.MainFrame.frame private
Definition at line 26 of file MainFrame.java.
Referenced by group17.weatherviewer.MainFrame.main().
label12AM
JLabel group17.weatherviewer.MainFrame.label12AM private
Definition at line 66 of file MainFrame.java.
label12AMPrecipitation
JLabel group17.weatherviewer.MainFrame.label12AMPrecipitation private
Definition at line 70 of file MainFrame.java.
label12AMSkyConditionIcon
JLabel group17.weatherviewer.MainFrame.label12AMSkyConditionIcon private
Definition at line 67 of file MainFrame.java.
label12AMSkyConditionInfo
JLabel group17.weatherviewer.MainFrame.label12AMSkyConditionInfo private
Definition at line 69 of file MainFrame.java.
label12AMTempInfo
JLabel group17.weatherviewer.MainFrame.label12AMTempInfo private
Definition at line 68 of file MainFrame.java.
label12PM
JLabel group17.weatherviewer.MainFrame.label12PM private
Definition at line 86 of file MainFrame.java.
label12PMPrecipitation
JLabel group17.weatherviewer.MainFrame.label12PMPrecipitation private
Definition at line 90 of file MainFrame.java.
label12PMSkyConditionIcon
JLabel group17.weatherviewer.MainFrame.label12PMSkyConditionIcon private
Definition at line 87 of file MainFrame.java.
label12PMSkyConditionInfo
JLabel group17.weatherviewer.MainFrame.label12PMSkyConditionInfo private
Definition at line 89 of file MainFrame.java.
label12PMTempInfo
JLabel group17.weatherviewer.MainFrame.label12PMTempInfo private
Definition at line 88 of file MainFrame.java.
label3AM
JLabel group17.weatherviewer.MainFrame.label3AM private
Definition at line 71 of file MainFrame.java.
label3AMPrecipitation
JLabel group17.weatherviewer.MainFrame.label3AMPrecipitation private
Definition at line 75 of file MainFrame.java.
label3AMSkyConditionIcon
JLabel group17.weatherviewer.MainFrame.label3AMSkyConditionIcon private
Definition at line 72 of file MainFrame.java.
label3AMSkyConditionInfo
JLabel group17.weatherviewer.MainFrame.label3AMSkyConditionInfo private
Definition at line 74 of file MainFrame.java.
label3AMTempInfo
JLabel group17.weatherviewer.MainFrame.label3AMTempInfo private
Definition at line 73 of file MainFrame.java.
label3PM
JLabel group17.weatherviewer.MainFrame.label3PM private
Definition at line 91 of file MainFrame.java.
label3PMPrecipitation
JLabel group17.weatherviewer.MainFrame.label3PMPrecipitation private
Definition at line 95 of file MainFrame.java.
label3PMSkyConditionIcon
JLabel group17.weatherviewer.MainFrame.label3PMSkyConditionIcon private
Definition at line 92 of file MainFrame.java.
label3PMSkyConditionInfo
JLabel group17.weatherviewer.MainFrame.label3PMSkyConditionInfo private
Definition at line 94 of file MainFrame.java.
label3PMTempInfo
JLabel group17.weatherviewer.MainFrame.label3PMTempInfo private
Definition at line 93 of file MainFrame.java.
label6AM
JLabel group17.weatherviewer.MainFrame.label6AM private
Definition at line 76 of file MainFrame.java.
label6AMPrecipitation
JLabel group17.weatherviewer.MainFrame.label6AMPrecipitation private
Definition at line 80 of file MainFrame.java.
label6AMSkyConditionIcon
JLabel group17.weatherviewer.MainFrame.label6AMSkyConditionIcon private
Definition at line 77 of file MainFrame.java.
label6AMSkyConditionInfo
JLabel group17.weatherviewer.MainFrame.label6AMSkyConditionInfo private
Definition at line 79 of file MainFrame.java.
label6AMTempInfo
JLabel group17.weatherviewer.MainFrame.label6AMTempInfo private
Definition at line 78 of file MainFrame.java.
label6PM
JLabel group17.weatherviewer.MainFrame.label6PM private
Definition at line 96 of file MainFrame.java.
label6PMPrecipitation
JLabel group17.weatherviewer.MainFrame.label6PMPrecipitation private
Definition at line 100 of file MainFrame.java.
label6PMSkyConditionIcon
JLabel group17.weatherviewer.MainFrame.label6PMSkyConditionIcon private
Definition at line 97 of file MainFrame.java.
label6PMSkyConditionInfo
JLabel group17.weatherviewer.MainFrame.label6PMSkyConditionInfo private
Definition at line 99 of file MainFrame.java.
label6PMTempInfo
JLabel group17.weatherviewer.MainFrame.label6PMTempInfo private
Definition at line 98 of file MainFrame.java.
label9AM
JLabel group17.weatherviewer.MainFrame.label9AM private
Definition at line 81 of file MainFrame.java.
label9AMPrecipitation
JLabel group17.weatherviewer.MainFrame.label9AMPrecipitation private
Definition at line 85 of file MainFrame.java.
label9AMSkyConditionIcon
JLabel group17.weatherviewer.MainFrame.label9AMSkyConditionIcon private
Definition at line 82 of file MainFrame.java.
label9AMSkyConditionInfo
JLabel group17.weatherviewer.MainFrame.label9AMSkyConditionInfo private
Definition at line 84 of file MainFrame.java.
label9AMTempInfo
JLabel group17.weatherviewer.MainFrame.label9AMTempInfo private
Definition at line 83 of file MainFrame.java.
label9PM
JLabel group17.weatherviewer.MainFrame.label9PM private
Definition at line 101 of file MainFrame.java.
label9PMPrecipitation
JLabel group17.weatherviewer.MainFrame.label9PMPrecipitation private
Definition at line 105 of file MainFrame.java.
label9PMSkyConditionIcon
JLabel group17.weatherviewer.MainFrame.label9PMSkyConditionIcon private
Definition at line 102 of file MainFrame.java.
label9PMSkyConditionInfo
JLabel group17.weatherviewer.MainFrame.label9PMSkyConditionInfo private
Definition at line 104 of file MainFrame.java.
label9PMTempInfo
JLabel group17.weatherviewer.MainFrame.label9PMTempInfo private
Definition at line 103 of file MainFrame.java.
labelAirPressure
JLabel group17.weatherviewer.MainFrame.labelAirPressure private
Definition at line 47 of file MainFrame.java.
labelAirPressureInfo
JLabel group17.weatherviewer.MainFrame.labelAirPressureInfo private
Definition at line 58 of file MainFrame.java.
labelCurrentMMTempInfo
JLabel group17.weatherviewer.MainFrame.labelCurrentMMTempInfo private
Definition at line 59 of file MainFrame.java.
labelDay1Info
JLabel group17.weatherviewer.MainFrame.labelDay1Info private
Definition at line 106 of file MainFrame.java.
labelDay1MMTempInfo
JLabel group17.weatherviewer.MainFrame.labelDay1MMTempInfo private
Definition at line 108 of file MainFrame.java.
labelDay1PrecipitationInfo
JLabel group17.weatherviewer.MainFrame.labelDay1PrecipitationInfo private
Definition at line 111 of file MainFrame.java.
labelDay1SkyConditionIcon
JLabel group17.weatherviewer.MainFrame.labelDay1SkyConditionIcon private
Definition at line 109 of file MainFrame.java.
labelDay1SkyConditionInfo
JLabel group17.weatherviewer.MainFrame.labelDay1SkyConditionInfo private
Definition at line 110 of file MainFrame.java.
labelDay1TempInfo
JLabel group17.weatherviewer.MainFrame.labelDay1TempInfo private
Definition at line 107 of file MainFrame.java.
labelDay2Info
JLabel group17.weatherviewer.MainFrame.labelDay2Info private
Definition at line 112 of file MainFrame.java.
labelDay2MMTempInfo
JLabel group17.weatherviewer.MainFrame.labelDay2MMTempInfo private
Definition at line 114 of file MainFrame.java.
labelDay2PrecipitationInfo
JLabel group17.weatherviewer.MainFrame.labelDay2PrecipitationInfo private
Definition at line 117 of file MainFrame.java.
labelDay2SkyConditionIcon
JLabel group17.weatherviewer.MainFrame.labelDay2SkyConditionIcon private
Definition at line 116 of file MainFrame.java.
labelDay2SkyConditionInfo
JLabel group17.weatherviewer.MainFrame.labelDay2SkyConditionInfo private
Definition at line 115 of file MainFrame.java.
labelDay2TempInfo
JLabel group17.weatherviewer.MainFrame.labelDay2TempInfo private
Definition at line 113 of file MainFrame.java.
labelDay3Info
JLabel group17.weatherviewer.MainFrame.labelDay3Info private
Definition at line 118 of file MainFrame.java.
labelDay3MMTempInfo
JLabel group17.weatherviewer.MainFrame.labelDay3MMTempInfo private
Definition at line 120 of file MainFrame.java.
labelDay3PrecipitationInfo
JLabel group17.weatherviewer.MainFrame.labelDay3PrecipitationInfo private
Definition at line 123 of file MainFrame.java.
labelDay3SkyConditionIcon
JLabel group17.weatherviewer.MainFrame.labelDay3SkyConditionIcon private
Definition at line 122 of file MainFrame.java.
labelDay3SkyConditionInfo
JLabel group17.weatherviewer.MainFrame.labelDay3SkyConditionInfo private
Definition at line 121 of file MainFrame.java.
labelDay3TempInfo
JLabel group17.weatherviewer.MainFrame.labelDay3TempInfo private
Definition at line 119 of file MainFrame.java.
labelDay4Info
JLabel group17.weatherviewer.MainFrame.labelDay4Info private
Definition at line 124 of file MainFrame.java.
labelDay4MMTempInfo
JLabel group17.weatherviewer.MainFrame.labelDay4MMTempInfo private
Definition at line 126 of file MainFrame.java.
labelDay4PrecipitationInfo
JLabel group17.weatherviewer.MainFrame.labelDay4PrecipitationInfo private
Definition at line 129 of file MainFrame.java.
labelDay4SkyConditionIcon
JLabel group17.weatherviewer.MainFrame.labelDay4SkyConditionIcon private
Definition at line 128 of file MainFrame.java.
labelDay4SkyConditionInfo
JLabel group17.weatherviewer.MainFrame.labelDay4SkyConditionInfo private
Definition at line 127 of file MainFrame.java.
labelDay4TempInfo
JLabel group17.weatherviewer.MainFrame.labelDay4TempInfo private
Definition at line 125 of file MainFrame.java.
labelDay5Info
JLabel group17.weatherviewer.MainFrame.labelDay5Info private
Definition at line 130 of file MainFrame.java.
labelDay5MMTempInfo
JLabel group17.weatherviewer.MainFrame.labelDay5MMTempInfo private
Definition at line 132 of file MainFrame.java.
labelDay5PrecipitationInfo
JLabel group17.weatherviewer.MainFrame.labelDay5PrecipitationInfo private
Definition at line 135 of file MainFrame.java.
labelDay5SkyConditionIcon
JLabel group17.weatherviewer.MainFrame.labelDay5SkyConditionIcon private
Definition at line 134 of file MainFrame.java.
labelDay5SkyConditionInfo
JLabel group17.weatherviewer.MainFrame.labelDay5SkyConditionInfo private
Definition at line 133 of file MainFrame.java.
labelDay5TempInfo
JLabel group17.weatherviewer.MainFrame.labelDay5TempInfo private
Definition at line 131 of file MainFrame.java.
labelDay6Info
JLabel group17.weatherviewer.MainFrame.labelDay6Info private
Definition at line 136 of file MainFrame.java.
labelDay6MMTempInfo
JLabel group17.weatherviewer.MainFrame.labelDay6MMTempInfo private
Definition at line 138 of file MainFrame.java.
labelDay6PrecipitationInfo
JLabel group17.weatherviewer.MainFrame.labelDay6PrecipitationInfo private
Definition at line 141 of file MainFrame.java.
labelDay6SkyConditionIcon
JLabel group17.weatherviewer.MainFrame.labelDay6SkyConditionIcon private
Definition at line 140 of file MainFrame.java.
labelDay6SkyConditionInfo
JLabel group17.weatherviewer.MainFrame.labelDay6SkyConditionInfo private
Definition at line 139 of file MainFrame.java.
labelDay6TempInfo
JLabel group17.weatherviewer.MainFrame.labelDay6TempInfo private
Definition at line 137 of file MainFrame.java.
labelDay7Info
JLabel group17.weatherviewer.MainFrame.labelDay7Info private
Definition at line 142 of file MainFrame.java.
labelDay7MMTempInfo
JLabel group17.weatherviewer.MainFrame.labelDay7MMTempInfo private
Definition at line 144 of file MainFrame.java.
labelDay7PrecipitationInfo
JLabel group17.weatherviewer.MainFrame.labelDay7PrecipitationInfo private
Definition at line 147 of file MainFrame.java.
labelDay7SkyConditionIcon
JLabel group17.weatherviewer.MainFrame.labelDay7SkyConditionIcon private
Definition at line 146 of file MainFrame.java.
labelDay7SkyConditionInfo
JLabel group17.weatherviewer.MainFrame.labelDay7SkyConditionInfo private
Definition at line 145 of file MainFrame.java.
labelDay7TempInfo
JLabel group17.weatherviewer.MainFrame.labelDay7TempInfo private
Definition at line 143 of file MainFrame.java.
labelHumidity
JLabel group17.weatherviewer.MainFrame.labelHumidity private
Definition at line 52 of file MainFrame.java.
labelHumidityInfo
JLabel group17.weatherviewer.MainFrame.labelHumidityInfo private
Definition at line 57 of file MainFrame.java.
labelLocation
JLabel group17.weatherviewer.MainFrame.labelLocation private
Definition at line 53 of file MainFrame.java.
labelPrecipitation
JLabel group17.weatherviewer.MainFrame.labelPrecipitation private
Definition at line 54 of file MainFrame.java.
labelPrecipitationInfo
JLabel group17.weatherviewer.MainFrame.labelPrecipitationInfo private
Definition at line 63 of file MainFrame.java.
labelSky
JLabel group17.weatherviewer.MainFrame.labelSky private
Definition at line 50 of file MainFrame.java.
labelSkyConditionIcon
JLabel group17.weatherviewer.MainFrame.labelSkyConditionIcon private
Definition at line 46 of file MainFrame.java.
labelSkyConditionInfo
JLabel group17.weatherviewer.MainFrame.labelSkyConditionInfo private
Definition at line 62 of file MainFrame.java.
labelSunrise
JLabel group17.weatherviewer.MainFrame.labelSunrise private
Definition at line 48 of file MainFrame.java.
labelSunriseInfo
JLabel group17.weatherviewer.MainFrame.labelSunriseInfo private
Definition at line 60 of file MainFrame.java.
labelSunset
JLabel group17.weatherviewer.MainFrame.labelSunset private
Definition at line 49 of file MainFrame.java.
labelSunsetInfo
JLabel group17.weatherviewer.MainFrame.labelSunsetInfo private
Definition at line 61 of file MainFrame.java.
labelTempInfo
JLabel group17.weatherviewer.MainFrame.labelTempInfo private
Definition at line 55 of file MainFrame.java.
labelUpdated
JLabel group17.weatherviewer.MainFrame.labelUpdated private
Definition at line 64 of file MainFrame.java.
labelUpdatedInfo
JLabel group17.weatherviewer.MainFrame.labelUpdatedInfo private
Definition at line 65 of file MainFrame.java.
labelWind
JLabel group17.weatherviewer.MainFrame.labelWind private
Definition at line 51 of file MainFrame.java.
labelWindInfo
JLabel group17.weatherviewer.MainFrame.labelWindInfo private
Definition at line 56 of file MainFrame.java.
lastUpdated
String group17.weatherviewer.MainFrame.lastUpdated private
Definition at line 151 of file MainFrame.java.
listLocations
JList group17.weatherviewer.MainFrame.listLocations private
Definition at line 153 of file MainFrame.java.
listModel
DefaultListModel group17.weatherviewer.MainFrame.listModel private
Definition at line 154 of file MainFrame.java.
longTermDate
ArrayList<JLabel> group17.weatherviewer.MainFrame.longTermDate = new ArrayList<JLabel>() private
Definition at line 168 of file MainFrame.java.
longTermForecast
LongTermForecast group17.weatherviewer.MainFrame.longTermForecast private
Definition at line 160 of file MainFrame.java.
longTermHighLow
ArrayList<JLabel> group17.weatherviewer.MainFrame.longTermHighLow = new ArrayList<JLabel>() private
Definition at line 172 of file MainFrame.java.
longTermIcon
ArrayList<JLabel> group17.weatherviewer.MainFrame.longTermIcon = new ArrayList<JLabel>() private
Definition at line 169 of file MainFrame.java.
longTermPrecip
ArrayList<JLabel> group17.weatherviewer.MainFrame.longTermPrecip = new ArrayList<JLabel>() private
Definition at line 173 of file MainFrame.java.
longTermSkyCon
ArrayList<JLabel> group17.weatherviewer.MainFrame.longTermSkyCon = new ArrayList<JLabel>() private
Definition at line 170 of file MainFrame.java.
longTermTemp
ArrayList<JLabel> group17.weatherviewer.MainFrame.longTermTemp = new ArrayList<JLabel>() private
Definition at line 171 of file MainFrame.java.
prefs
UserPreferences group17.weatherviewer.MainFrame.prefs private
Definition at line 156 of file MainFrame.java.
scrollPane
JScrollPane group17.weatherviewer.MainFrame.scrollPane private
Definition at line 38 of file MainFrame.java.
shortTermForecast
ShortTermForecast group17.weatherviewer.MainFrame.shortTermForecast private
Definition at line 159 of file MainFrame.java.
shortTermIcon
ArrayList<JLabel> group17.weatherviewer.MainFrame.shortTermIcon = new ArrayList<JLabel>() private
Definition at line 163 of file MainFrame.java.
shortTermPrecip
ArrayList<JLabel> group17.weatherviewer.MainFrame.shortTermPrecip = new ArrayList<JLabel>() private
Definition at line 166 of file MainFrame.java.
shortTermSkyCon
ArrayList<JLabel> group17.weatherviewer.MainFrame.shortTermSkyCon = new ArrayList<JLabel>() private
Definition at line 164 of file MainFrame.java.
shortTermTemp
ArrayList<JLabel> group17.weatherviewer.MainFrame.shortTermTemp = new ArrayList<JLabel>() private
Definition at line 165 of file MainFrame.java.
shortTermTime
ArrayList<JLabel> group17.weatherviewer.MainFrame.shortTermTime = new ArrayList<JLabel>() private
Definition at line 162 of file MainFrame.java.
skyConditionBackground
String group17.weatherviewer.MainFrame.skyConditionBackground private
Definition at line 31 of file MainFrame.java.
skyConditionIconLarge
String group17.weatherviewer.MainFrame.skyConditionIconLarge private
Definition at line 29 of file MainFrame.java.
skyConditionIconSmall
String group17.weatherviewer.MainFrame.skyConditionIconSmall private
Definition at line 30 of file MainFrame.java.
textField
JTextField group17.weatherviewer.MainFrame.textField private
Definition at line 35 of file MainFrame.java.
The documentation for this class was generated from the following file:
weatherviewer/MainFrame.java