Evoluzione_Doxygen_Base: group17.weatherviewer.ShortTermForecast.ShortTermWeather Class Reference
group17.weatherviewer.ShortTermForecast.ShortTermWeather Class Reference
Public Member Functions
ShortTermWeather (String time, String skycon, double temp, double rain, double snow, int weatherID)
String getTime ()
String getSkyCon ()
String getTemp (char tempUnit)
String getRain ()
String getSnow ()
String getSkyCondition ()
int getWeatherID ()
Package Attributes
String skycon
double rain
double snow
Private Member Functions
String cleanTemp (double t, char unit)
Private Attributes
String time
double temp
int weatherID
Detailed Description
Definition at line 95 of file ShortTermForecast.java.
Constructor & Destructor Documentation
ShortTermWeather()
group17.weatherviewer.ShortTermForecast.ShortTermWeather.ShortTermWeather (String time, String skycon, double temp, double rain, double snow, int weatherID) inline
Definition at line 100 of file ShortTermForecast.java.
References group17.weatherviewer.ShortTermForecast.ShortTermWeather.rain, group17.weatherviewer.ShortTermForecast.ShortTermWeather.skycon, group17.weatherviewer.ShortTermForecast.ShortTermWeather.snow, group17.weatherviewer.ShortTermForecast.ShortTermWeather.temp, group17.weatherviewer.ShortTermForecast.ShortTermWeather.time, and group17.weatherviewer.ShortTermForecast.ShortTermWeather.weatherID.
Member Function Documentation
cleanTemp()
String group17.weatherviewer.ShortTermForecast.ShortTermWeather.cleanTemp (double t, char unit) inline private
Definition at line 131 of file ShortTermForecast.java.
Referenced by group17.weatherviewer.ShortTermForecast.ShortTermWeather.getTemp().
getRain()
String group17.weatherviewer.ShortTermForecast.ShortTermWeather.getRain () inline
Definition at line 145 of file ShortTermForecast.java.
Referenced by group17.weatherviewer.MainFrame.updateShortTerm().
getSkyCon()
String group17.weatherviewer.ShortTermForecast.ShortTermWeather.getSkyCon () inline
Definition at line 115 of file ShortTermForecast.java.
References group17.weatherviewer.ShortTermForecast.ShortTermWeather.skycon.
getSkyCondition()
String group17.weatherviewer.ShortTermForecast.ShortTermWeather.getSkyCondition () inline
Definition at line 159 of file ShortTermForecast.java.
Referenced by group17.weatherviewer.MainFrame.updateShortTerm().
getSnow()
String group17.weatherviewer.ShortTermForecast.ShortTermWeather.getSnow () inline
Definition at line 152 of file ShortTermForecast.java.
Referenced by group17.weatherviewer.MainFrame.updateShortTerm().
getTemp()
String group17.weatherviewer.ShortTermForecast.ShortTermWeather.getTemp (char tempUnit) inline
Getter method for Celsius temperature
Returns
the current temp in degrees C (will be only temp method in later versions)
Definition at line 123 of file ShortTermForecast.java.
References group17.weatherviewer.ShortTermForecast.ShortTermWeather.cleanTemp().
Referenced by group17.weatherviewer.MainFrame.setTemperatureFields().
getTime()
String group17.weatherviewer.ShortTermForecast.ShortTermWeather.getTime () inline
Definition at line 111 of file ShortTermForecast.java.
References group17.weatherviewer.ShortTermForecast.ShortTermWeather.time.
Referenced by group17.weatherviewer.MainFrame.updateShortTerm().
getWeatherID()
int group17.weatherviewer.ShortTermForecast.ShortTermWeather.getWeatherID () inline
Definition at line 163 of file ShortTermForecast.java.
References group17.weatherviewer.ShortTermForecast.ShortTermWeather.weatherID.
Referenced by group17.weatherviewer.MainFrame.updateShortTerm().
Field Documentation
rain
double group17.weatherviewer.ShortTermForecast.ShortTermWeather.rain package
Definition at line 97 of file ShortTermForecast.java.
Referenced by group17.weatherviewer.ShortTermForecast.ShortTermWeather.ShortTermWeather().
skycon
String group17.weatherviewer.ShortTermForecast.ShortTermWeather.skycon package
Definition at line 96 of file ShortTermForecast.java.
Referenced by group17.weatherviewer.ShortTermForecast.ShortTermWeather.getSkyCon(), and group17.weatherviewer.ShortTermForecast.ShortTermWeather.ShortTermWeather().
snow
double group17.weatherviewer.ShortTermForecast.ShortTermWeather.snow package
Definition at line 97 of file ShortTermForecast.java.
Referenced by group17.weatherviewer.ShortTermForecast.ShortTermWeather.ShortTermWeather().
temp
double group17.weatherviewer.ShortTermForecast.ShortTermWeather.temp private
Definition at line 97 of file ShortTermForecast.java.
Referenced by group17.weatherviewer.ShortTermForecast.ShortTermWeather.ShortTermWeather().
time
String group17.weatherviewer.ShortTermForecast.ShortTermWeather.time private
Definition at line 96 of file ShortTermForecast.java.
Referenced by group17.weatherviewer.ShortTermForecast.ShortTermWeather.getTime(), and group17.weatherviewer.ShortTermForecast.ShortTermWeather.ShortTermWeather().
weatherID
int group17.weatherviewer.ShortTermForecast.ShortTermWeather.weatherID private
Definition at line 98 of file ShortTermForecast.java.
Referenced by group17.weatherviewer.ShortTermForecast.ShortTermWeather.getWeatherID(), and group17.weatherviewer.ShortTermForecast.ShortTermWeather.ShortTermWeather().
The documentation for this class was generated from the following file:
weatherviewer/ShortTermForecast.java