Evoluzione_Doxygen_Base: group17.weatherviewer.LongTermForecast.LongTermWeather Class Reference
group17.weatherviewer.LongTermForecast.LongTermWeather Class Reference
Public Member Functions
LongTermWeather (String date, String skycon, double temp, double high, double low, double rain, double snow, int weatherID)
String getDate ()
String getTemp (char tempUnit)
String getHigh (char tempUnit)
String getLow (char tempUnit)
String getRain ()
String getSnow ()
String getSkyCondition ()
int getWeatherID ()
Package Attributes
String skycon
double high
double low
double rain
double snow
Private Member Functions
String cleanTemp (double t, char unit)
Private Attributes
String date
double temp
int weatherID
Detailed Description
Data type that contains longterm weather data
Definition at line 101 of file LongTermForecast.java.
Constructor & Destructor Documentation
LongTermWeather()
group17.weatherviewer.LongTermForecast.LongTermWeather.LongTermWeather (String date, String skycon, double temp, double high, double low, double rain, double snow, int weatherID) inline
Definition at line 106 of file LongTermForecast.java.
References group17.weatherviewer.LongTermForecast.LongTermWeather.high, group17.weatherviewer.LongTermForecast.LongTermWeather.low, group17.weatherviewer.LongTermForecast.LongTermWeather.rain, group17.weatherviewer.LongTermForecast.LongTermWeather.skycon, group17.weatherviewer.LongTermForecast.LongTermWeather.snow, group17.weatherviewer.LongTermForecast.LongTermWeather.temp, group17.weatherviewer.Conversion.unixToDate(), and group17.weatherviewer.LongTermForecast.LongTermWeather.weatherID.
Member Function Documentation
cleanTemp()
String group17.weatherviewer.LongTermForecast.LongTermWeather.cleanTemp (double t, char unit) inline private
Definition at line 149 of file LongTermForecast.java.
Referenced by group17.weatherviewer.LongTermForecast.LongTermWeather.getHigh(), group17.weatherviewer.LongTermForecast.LongTermWeather.getLow(), and group17.weatherviewer.LongTermForecast.LongTermWeather.getTemp().
getDate()
String group17.weatherviewer.LongTermForecast.LongTermWeather.getDate () inline
Definition at line 119 of file LongTermForecast.java.
References group17.weatherviewer.LongTermForecast.LongTermWeather.date.
Referenced by group17.weatherviewer.MainFrame.updateLongTerm().
getHigh()
String group17.weatherviewer.LongTermForecast.LongTermWeather.getHigh (char tempUnit) inline
Definition at line 134 of file LongTermForecast.java.
References group17.weatherviewer.LongTermForecast.LongTermWeather.cleanTemp().
Referenced by group17.weatherviewer.MainFrame.setTemperatureFields().
getLow()
String group17.weatherviewer.LongTermForecast.LongTermWeather.getLow (char tempUnit) inline
Definition at line 141 of file LongTermForecast.java.
References group17.weatherviewer.LongTermForecast.LongTermWeather.cleanTemp().
Referenced by group17.weatherviewer.MainFrame.setTemperatureFields().
getRain()
String group17.weatherviewer.LongTermForecast.LongTermWeather.getRain () inline
Definition at line 163 of file LongTermForecast.java.
Referenced by group17.weatherviewer.MainFrame.updateLongTerm().
getSkyCondition()
String group17.weatherviewer.LongTermForecast.LongTermWeather.getSkyCondition () inline
Definition at line 177 of file LongTermForecast.java.
Referenced by group17.weatherviewer.MainFrame.updateLongTerm().
getSnow()
String group17.weatherviewer.LongTermForecast.LongTermWeather.getSnow () inline
Definition at line 170 of file LongTermForecast.java.
Referenced by group17.weatherviewer.MainFrame.updateLongTerm().
getTemp()
String group17.weatherviewer.LongTermForecast.LongTermWeather.getTemp (char tempUnit) inline
Getter method for Celsius temperature
Returns
the current temp in degrees C (will be only temp method in later versions)
Definition at line 127 of file LongTermForecast.java.
References group17.weatherviewer.LongTermForecast.LongTermWeather.cleanTemp().
Referenced by group17.weatherviewer.MainFrame.setTemperatureFields().
getWeatherID()
int group17.weatherviewer.LongTermForecast.LongTermWeather.getWeatherID () inline
Definition at line 181 of file LongTermForecast.java.
References group17.weatherviewer.LongTermForecast.LongTermWeather.weatherID.
Referenced by group17.weatherviewer.MainFrame.updateLongTerm().
Field Documentation
date
String group17.weatherviewer.LongTermForecast.LongTermWeather.date private
Definition at line 102 of file LongTermForecast.java.
Referenced by group17.weatherviewer.LongTermForecast.LongTermWeather.getDate().
high
double group17.weatherviewer.LongTermForecast.LongTermWeather.high package
Definition at line 103 of file LongTermForecast.java.
Referenced by group17.weatherviewer.LongTermForecast.LongTermWeather.LongTermWeather().
low
double group17.weatherviewer.LongTermForecast.LongTermWeather.low package
Definition at line 103 of file LongTermForecast.java.
Referenced by group17.weatherviewer.LongTermForecast.LongTermWeather.LongTermWeather().
rain
double group17.weatherviewer.LongTermForecast.LongTermWeather.rain package
Definition at line 103 of file LongTermForecast.java.
Referenced by group17.weatherviewer.LongTermForecast.LongTermWeather.LongTermWeather().
skycon
String group17.weatherviewer.LongTermForecast.LongTermWeather.skycon package
Definition at line 102 of file LongTermForecast.java.
Referenced by group17.weatherviewer.LongTermForecast.LongTermWeather.LongTermWeather().
snow
double group17.weatherviewer.LongTermForecast.LongTermWeather.snow package
Definition at line 103 of file LongTermForecast.java.
Referenced by group17.weatherviewer.LongTermForecast.LongTermWeather.LongTermWeather().
temp
double group17.weatherviewer.LongTermForecast.LongTermWeather.temp private
Definition at line 103 of file LongTermForecast.java.
Referenced by group17.weatherviewer.LongTermForecast.LongTermWeather.LongTermWeather().
weatherID
int group17.weatherviewer.LongTermForecast.LongTermWeather.weatherID private
Definition at line 104 of file LongTermForecast.java.
Referenced by group17.weatherviewer.LongTermForecast.LongTermWeather.getWeatherID(), and group17.weatherviewer.LongTermForecast.LongTermWeather.LongTermWeather().
The documentation for this class was generated from the following file:
weatherviewer/LongTermForecast.java