Evoluzione_Doxygen_Base: group17.weatherviewer.ShortTermForecast Class Reference
group17.weatherviewer.ShortTermForecast Class Reference
Data Structures
class ShortTermWeather
Public Member Functions
ShortTermForecast (String cityName) throws UnsupportedEncodingException
String getTotalPrecipitation ()
ArrayList< ShortTermWeather > getShortTermForecast ()
Package Attributes
String skyCon
double rain
double snow
double totalSnow = 0
Private Attributes
String time
double temp
double totalRain = 0
int weatherID
ArrayList< ShortTermWeather > shortTermForecast = new ArrayList<ShortTermWeather>()
Detailed Description
Definition at line 9 of file ShortTermForecast.java.
Constructor & Destructor Documentation
ShortTermForecast()
group17.weatherviewer.ShortTermForecast.ShortTermForecast (String cityName) throws UnsupportedEncodingException inline
Definition at line 19 of file ShortTermForecast.java.
References group17.weatherviewer.JsonParser.getData(), group17.weatherviewer.ShortTermForecast.rain, group17.weatherviewer.ShortTermForecast.snow, and group17.weatherviewer.ShortTermForecast.totalSnow.
Member Function Documentation
getShortTermForecast()
ArrayList<ShortTermWeather> group17.weatherviewer.ShortTermForecast.getShortTermForecast () inline
Definition at line 90 of file ShortTermForecast.java.
References group17.weatherviewer.ShortTermForecast.shortTermForecast.
Referenced by group17.weatherviewer.MainFrame.setTemperatureFields(), and group17.weatherviewer.MainFrame.updateShortTerm().
getTotalPrecipitation()
String group17.weatherviewer.ShortTermForecast.getTotalPrecipitation () inline
Definition at line 80 of file ShortTermForecast.java.
References group17.weatherviewer.ShortTermForecast.totalSnow.
Referenced by group17.weatherviewer.MainFrame.refresh().
Field Documentation
rain
double group17.weatherviewer.ShortTermForecast.rain package
Definition at line 12 of file ShortTermForecast.java.
Referenced by group17.weatherviewer.ShortTermForecast.ShortTermForecast().
shortTermForecast
ArrayList<ShortTermWeather> group17.weatherviewer.ShortTermForecast.shortTermForecast = new ArrayList<ShortTermWeather>() private
Definition at line 17 of file ShortTermForecast.java.
Referenced by group17.weatherviewer.ShortTermForecast.getShortTermForecast().
skyCon
String group17.weatherviewer.ShortTermForecast.skyCon package
Definition at line 11 of file ShortTermForecast.java.
snow
double group17.weatherviewer.ShortTermForecast.snow package
Definition at line 12 of file ShortTermForecast.java.
Referenced by group17.weatherviewer.ShortTermForecast.ShortTermForecast().
temp
double group17.weatherviewer.ShortTermForecast.temp private
Definition at line 12 of file ShortTermForecast.java.
time
String group17.weatherviewer.ShortTermForecast.time private
Definition at line 11 of file ShortTermForecast.java.
totalRain
double group17.weatherviewer.ShortTermForecast.totalRain = 0 private
Definition at line 13 of file ShortTermForecast.java.
totalSnow
double group17.weatherviewer.ShortTermForecast.totalSnow = 0 package
Definition at line 13 of file ShortTermForecast.java.
Referenced by group17.weatherviewer.ShortTermForecast.getTotalPrecipitation(), and group17.weatherviewer.ShortTermForecast.ShortTermForecast().
weatherID
int group17.weatherviewer.ShortTermForecast.weatherID private
Definition at line 14 of file ShortTermForecast.java.
The documentation for this class was generated from the following file:
weatherviewer/ShortTermForecast.java