Evoluzione_Doxygen_Base: group17.weatherviewer.UserPreferences Class Reference
group17.weatherviewer.UserPreferences Class Reference
Public Member Functions
UserPreferences ()
void setTempUnit (char unit)
void setDefaultLocation (String location)
char getTempUnit ()
ArrayList< String > getLocations ()
String getDefaultLocation ()
boolean addLocation (int index, String s)
Static Public Member Functions
static void savePrefs (UserPreferences up)
static UserPreferences getPrefs ()
Private Attributes
char tempUnit
ArrayList< String > locations
String defaultLocation
Static Private Attributes
static final transient String FILENAME = "weather.prefs"
static final long serialVersionUID = 5423608160937997909L
Detailed Description
Definition at line 6 of file UserPreferences.java.
Constructor & Destructor Documentation
UserPreferences()
group17.weatherviewer.UserPreferences.UserPreferences () inline
Constructor of user preferences, initializes locations list and sets default values
Definition at line 20 of file UserPreferences.java.
Referenced by group17.weatherviewer.UserPreferences.getPrefs().
Member Function Documentation
addLocation()
boolean group17.weatherviewer.UserPreferences.addLocation (int index, String s) inline
Adds a location to the list of favorite locations in a certain position
Parameters
index provides where in the list the element should be added
s name of the location
Returns
false if the adding failed, true otherwise
Definition at line 74 of file UserPreferences.java.
Referenced by group17.weatherviewer.MainFrame.AddLocation.actionPerformed().
getDefaultLocation()
String group17.weatherviewer.UserPreferences.getDefaultLocation () inline
Gets defaultLocation
Returns
the default location
Definition at line 64 of file UserPreferences.java.
References group17.weatherviewer.UserPreferences.defaultLocation.
Referenced by group17.weatherviewer.MainFrame.initialize().
getLocations()
ArrayList<String> group17.weatherviewer.UserPreferences.getLocations () inline
Gets location list
Returns
an ArrayList<String> of locations
Definition at line 56 of file UserPreferences.java.
References group17.weatherviewer.UserPreferences.locations.
Referenced by group17.weatherviewer.MainFrame.initialize().
getPrefs()
static UserPreferences group17.weatherviewer.UserPreferences.getPrefs () inline static
Finds the FILENAME file in the working directory and loaded the serialized object, then returns it. Allows loading of preferences at the start of a program run.
Definition at line 104 of file UserPreferences.java.
References group17.weatherviewer.UserPreferences.UserPreferences().
Referenced by group17.weatherviewer.MainFrame.initialize().
getTempUnit()
char group17.weatherviewer.UserPreferences.getTempUnit () inline
Gets temperature unit
Returns
c for celsius, f for fahrenheit
Definition at line 49 of file UserPreferences.java.
References group17.weatherviewer.UserPreferences.tempUnit.
Referenced by group17.weatherviewer.MainFrame.initialize(), and group17.weatherviewer.MainFrame.setTemperatureFields().
savePrefs()
static void group17.weatherviewer.UserPreferences.savePrefs (UserPreferences up) inline static
Saves a copy of the provided preferences object to the working directory in a file called FILENAME.
Parameters
up is the preferences object to be serialized to a file for the next run.
Definition at line 87 of file UserPreferences.java.
Referenced by group17.weatherviewer.MainFrame.initialize().
setDefaultLocation()
void group17.weatherviewer.UserPreferences.setDefaultLocation (String location) inline
Sets default location to the last selected location
Parameters
location string representing the new default location
Definition at line 42 of file UserPreferences.java.
Referenced by group17.weatherviewer.MainFrame.initialize().
setTempUnit()
void group17.weatherviewer.UserPreferences.setTempUnit (char unit) inline
Sets temperature type to celsius (c) or fahrenheit (f) we can trust that the appropriate units are given because the user has no input for this
Parameters
unit char to indicate temperature type, can be either celsius (c) or fahrenheit (f)
Definition at line 32 of file UserPreferences.java.
Referenced by group17.weatherviewer.MainFrame.initialize().
Field Documentation
defaultLocation
String group17.weatherviewer.UserPreferences.defaultLocation private
Definition at line 15 of file UserPreferences.java.
Referenced by group17.weatherviewer.UserPreferences.getDefaultLocation().
FILENAME
final transient String group17.weatherviewer.UserPreferences.FILENAME = "weather.prefs" static private
Definition at line 9 of file UserPreferences.java.
locations
ArrayList<String> group17.weatherviewer.UserPreferences.locations private
Definition at line 14 of file UserPreferences.java.
Referenced by group17.weatherviewer.UserPreferences.getLocations().
serialVersionUID
final long group17.weatherviewer.UserPreferences.serialVersionUID = 5423608160937997909L static private
Definition at line 11 of file UserPreferences.java.
tempUnit
char group17.weatherviewer.UserPreferences.tempUnit private
Definition at line 13 of file UserPreferences.java.
Referenced by group17.weatherviewer.UserPreferences.getTempUnit().
The documentation for this class was generated from the following file:
weatherviewer/UserPreferences.java