Evoluzione_Doxygen_Base: group17.weatherviewer.LongTermForecast Class Reference
group17.weatherviewer.LongTermForecast Class Reference
Data Structures
class LongTermWeather
Public Member Functions
LongTermForecast (String cityName, int Term) throws UnsupportedEncodingException
ArrayList< LongTermWeather > getLongTermForecast ()
Package Attributes
String skyCon
double high
double low
double rain
double snow
Private Attributes
String date
double temp
int weatherID
ArrayList< LongTermWeather > longTermForecast = new ArrayList<>()
Detailed Description
Definition at line 15 of file LongTermForecast.java.
Constructor & Destructor Documentation
LongTermForecast()
group17.weatherviewer.LongTermForecast.LongTermForecast (String cityName, int Term) throws UnsupportedEncodingException inline
Retrieves long term weather data and constructs a LongTermForecast object from the JSON returned
Parameters
cityName the city to retrieve weather data for
Term number of days to retrieve data for
Exceptions
UnsupportedEncodingException if the api call is not valid
Definition at line 30 of file LongTermForecast.java.
References group17.weatherviewer.JsonParser.getData().
Member Function Documentation
getLongTermForecast()
ArrayList<LongTermWeather> group17.weatherviewer.LongTermForecast.getLongTermForecast () inline
Returns
a reference to the arraylist of long term weathers, ie returns all the retrieved data in java object form
Definition at line 94 of file LongTermForecast.java.
References group17.weatherviewer.LongTermForecast.longTermForecast.
Referenced by group17.weatherviewer.MainFrame.setTemperatureFields(), and group17.weatherviewer.MainFrame.updateLongTerm().
Field Documentation
date
String group17.weatherviewer.LongTermForecast.date private
Definition at line 17 of file LongTermForecast.java.
high
double group17.weatherviewer.LongTermForecast.high package
Definition at line 18 of file LongTermForecast.java.
longTermForecast
ArrayList<LongTermWeather> group17.weatherviewer.LongTermForecast.longTermForecast = new ArrayList<>() private
Definition at line 22 of file LongTermForecast.java.
Referenced by group17.weatherviewer.LongTermForecast.getLongTermForecast().
low
double group17.weatherviewer.LongTermForecast.low package
Definition at line 18 of file LongTermForecast.java.
rain
double group17.weatherviewer.LongTermForecast.rain package
Definition at line 18 of file LongTermForecast.java.
skyCon
String group17.weatherviewer.LongTermForecast.skyCon package
Definition at line 17 of file LongTermForecast.java.
snow
double group17.weatherviewer.LongTermForecast.snow package
Definition at line 18 of file LongTermForecast.java.
temp
double group17.weatherviewer.LongTermForecast.temp private
Definition at line 18 of file LongTermForecast.java.
weatherID
int group17.weatherviewer.LongTermForecast.weatherID private
Definition at line 19 of file LongTermForecast.java.
The documentation for this class was generated from the following file:
weatherviewer/LongTermForecast.java